# Etapa de construcción
#FROM node:18 AS builder

#WORKDIR /app

#COPY package.json package-lock.json ./
#RUN npm install

#COPY . .
#RUN npm run build

# Etapa de desarrollo
FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173 
CMD ["npm", "run", "dev"]